create database DoTheThao1
go
use DoTheThao1
go

create table NhanVien(
	MANV CHAR(10) PRIMARY KEY,
	HOTENNV NVARCHAR(255),
	GIOITINH BIT,
	NGAYSINHNV DATETIME,
	CHUCVU NVARCHAR(200),
	DIACHINV NVARCHAR(255),
	EMAIL VARCHAR(150),
	SODIENTHOAI VARCHAR(20),
	GHICHU NTEXT,
	XOA BIT
)
go
CREATE TABLE TaiKhoan(
	id int primary key IDENTITY(1,1),
	TENTAIKHOAN VARCHAR(100),
	MATKHAU VARCHAR(50),
	MANV CHAR(10),
	QUYEN NVARCHAR(200),
	XOA BIT
)
go
CReate table KhachHang(
	MAKH CHAR(10) PRIMARY KEY,
	HOTENKH NVARCHAR(255),
	GIOITINH BIT, 
	NGAYSINHKH DATETIME,
	DIACHIKH NVARCHAR(255),
	EMAIL VARCHAR(150),
	SODIENTHOAI VARCHAR(20),
	GHICHU NTEXT,
	XOA BIT 
)
go
create table SanPham(
	MASP CHAR(10) PRIMARY KEY,
	TENSP NVARCHAR(200),
	MALOAISP INT,
	MANSX INT,
	SOLUONG INT,
	SIZE NVARCHAR(50),
	PATHH nvarchar(200),
	DONGIA INT,
	MOTA NTEXT,
	GHICHU NTEXT,
	XOA BIT
)
go
create table LoaiSP(
	MALOAISP INT PRIMARY KEY,
	TENLOAISP NVARCHAR(100),
	GHICHU NTEXT,
	XOA BIT
)
go
create table NhaSanXuat(
	MANSX INT PRIMARY KEY IDENTITY(1,1),
	TENNSX NVARCHAR(255),
	WEBSITE VARCHAR(50),
	EMAIL VARCHAR(50),
	GHICHU NTEXT,
	XOA BIT
)
go
create table HoaDonBan(
	MAHD INT PRIMARY KEY Identity(1,1),
	NGAYBAN DATETIME,
	MANV CHAR(10),
	MAKH CHAR(10),
	TONGTIEN INT,
	GHICHU NTEXT,
	XOA BIT
)
go
create table CTHoaDon(
    ID int not null primary key IDENTITY(1,1),
	MAHD INT,
	MASP CHAR(10),
	SOLUONG INT,
	DONGIA INT,
	THANHTIEN INT,
	XOA BIT,
)
go